### ISSUE TITLE
Training & Automation Treasury Set-Up

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Auditing/Training-and-Automation-Coordination#18]
## Training & Automation Treasury
- [x] Create a Training & Automation Treasury wallet - Andre / Miro
- To hold remaining funds from F6 Distributed Auditability & F6 Open Source Training
- [x] F6 Distributed Auditability becomes Training & Automation Treasury wallet

## Closing down expenses from the old wallets
- [x] https://github.com/Catalyst-Auditing/Training-and-Automation-Coordination/issues/19
- [x] https://github.com/Catalyst-Auditing/Training-and-Automation-Coordination/issues/22

## Training & Automation Treasury wallet
The old F6 funds will go into a separate account. So that the fiat value loss can reported in the final report and Training & Automation can convert to Stablecoin if and when the price reaches $ 1.30
- [x] Separate account for old ADA funds - target price for conversion (Stablecoin or Fiat) 17th December $ 1.30
- [x] Two separate accounts in the Training & Automation Treasury wallet for the F6 Open source & F6 Distributed Audit proposals
-  We decided to keep the funds in one account to keep documentation simple.

## Fund 8 Proposals
- [x] F6 Open Source Training wallet becomes F8 Automate wallet
- [x] F8 ABC of Governance wallet is already setup - pass on seed phrases to Treasury

**Comment by Andre-Diamond** [comment]
Multisig wallet an option? - [ADAO-Roundtable](https://roundtable.theadao.io)
Tutorial - [Youtube Tutorial](https://www.youtube.com/watch?v=8bYsAwIofpY)
