### ISSUE TITLE
F6 Distributed Auditability - Outstanding charges for work to date and payments

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Auditing/Training-and-Automation-Coordination#19]
- Andre to review all automation tasks to date and provide charges total to close out F6 Distributed Auditability proposal

**Comment by Andre-Diamond** [comment]
[Invoice](https://docs.google.com/spreadsheets/d/1QZTwNONcRGSnqlVKjT3zL1kfdAKVi7uJpK7vmaAHMpQ/edit?usp=sharing) for tasks done to date.

**Comment by stephen-rowan** [comment]
Process question -

Should people follow the same format and send content via another format

**Comment by Andre-Diamond** [comment]
Payment here - https://treasury-guild.gitbook.io/training-and-automation/
