### ISSUE TITLE
F6 Open Source Training - Outstanding charges for work to date and payments

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Auditing/Training-and-Automation-Coordination#22]
- Stephen to collate charges for F6 Open Source Training to close out proposal
- https://github.com/Catalyst-Auditing/Training-and-Automation-Coordination/issues/20

**Comment by stephen-rowan** [comment]
## Outstanding Charges Estimate




- GitBook setup and regular maintenance - November 2021 to May 2022
- Open-source-training - Overview
- https://quality-assurance-dao.gitbook.io/training-and-automation/open-source-training/overview

**Comment by stephen-rowan** [comment]
- [ ] Pay Stephen the balance of the Invoice
- [ ] Keep remainder in separate account

**Comment by Andre-Diamond** [comment]
Payment - https://treasury-guild.gitbook.io/training-and-automation/
