### ISSUE TITLE
Obsidian Costs for 1 Month

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Auditing/Training-and-Automation-Coordination#31]
## Obsidian Sync

![Image](https://user-images.githubusercontent.com/25156451/170594366-ab455a77-a1fa-4b2d-959c-46d52dad2a07.png)

## Obsidian Publish

![Image](https://user-images.githubusercontent.com/25156451/170594377-18f2be70-689a-4fda-99d7-2f2fb4dabb8a.png)

## Annual Bill

Will pay annual advance on June 23rd 2022

**Comment by Andre-Diamond** [comment]
https://treasury-guild.gitbook.io/training-and-automation/transactions/fund-8/abc-of-governance
