### ISSUE TITLE
Setup Google Analytics on Training & Automation GitBook

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Auditing/Training-and-Automation-Coordination#43]
[Admin Section](https://github.com/Catalyst-Auditing/Training-and-Automation-Coordination/issues/43#issuecomment-1156501448)
[Analytics - 1](https://github.com/Catalyst-Auditing/Training-and-Automation-Coordination/issues/43#issuecomment-1156503956)
[Analytics - 2](https://github.com/Catalyst-Auditing/Training-and-Automation-Coordination/issues/43#issuecomment-1156505738)
[Tracking ID](https://github.com/Catalyst-Auditing/Training-and-Automation-Coordination/issues/43#issuecomment-1156510066)
[Space Custom](https://github.com/Catalyst-Auditing/Training-and-Automation-Coordination/issues/43#issuecomment-1156512608)

**Comment by Andre-Diamond** [comment]
![Image](https://user-images.githubusercontent.com/32074058/173844295-dae54b40-15d4-4b1a-8684-d58bebc9e9d8.png)

**Comment by Andre-Diamond** [comment]
![Image](https://user-images.githubusercontent.com/32074058/173844620-a8f0e0a8-88d5-4218-8dcb-f02c7f0777f2.png)

**Comment by Andre-Diamond** [comment]
![Image](https://user-images.githubusercontent.com/32074058/173846014-157159b4-b1cc-4725-b931-bc54f7f9fb05.png)
